//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Top20Video.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class language
    {
        public int id { get; set; }
        public string relevanceLanguage { get; set; }
        public string status { get; set; }
        public string RelevanceLanguageName { get; set; }
    }
}
