//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Top20Video.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbTop20Video_9359Entities : DbContext
    {
        public dbTop20Video_9359Entities()
            : base("name=dbTop20Video_9359Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminUser> AdminUsers { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<EventLog> EventLogs { get; set; }
        public DbSet<SyncSetting> SyncSettings { get; set; }
        public DbSet<Video> Videos { get; set; }
        public DbSet<Trending> Trendings { get; set; }
        public DbSet<language> languages { get; set; }
    }
}
